config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'onboarding#diagnostic'

  namespace :onboarding do
    get 'diagnostic', action: 'diagnostic'
    post 'sign_up_options'
    post 'new_sign_up'  #it has this posts as it needs to pass the user info
    post 'sign_up'
    get 'diagnostic_results'
    get 'suggested_programs'
    get 'program_detail/:program_id', action: 'program_detail'
    get 'choose_subscription/:program_id', action: 'choose_subscription'
    get 'pay_selected_plan', action: 'pay_selected_plan'
    post 'subscribe_stripe', action: 'subscribe_stripe'
  end

  namespace :buy_subscription do
    get 'offer_login'
    get 'suggested_programs'
    get 'more_programs'
    get 'program_detail'
    get 'choose_subscription'
    get 'payment_page'
    post 'subscribe_stripe'
    get 'lite_option'
    get 'thank_you_page'
    get 'upsale'
  end

 
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'
  # devise_for :users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth'
  }

  authenticate :user, -> (u) { u.is_admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'unauthorized', to: 'errors#unauthorized'
  # onboarding
  
end

app/models/program.rb
# == Schema Information
#
# Table name: programs
#
#  id              :bigint           not null, primary key
#  user_id         :bigint
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  pro             :boolean          default(TRUE), not null
#  available       :boolean          default(FALSE)
#  strength        :integer          default(0)
#  endurance       :integer          default(0)
#  technique       :integer          default(0)
#  flexibility     :integer          default(0)
#  intensity       :integer          default(0)
#  code_name       :string
#  name_es         :string
#  name_en         :string
#  description_en  :string
#  description_es  :string
#  auto_generated  :boolean          default(FALSE)
#  priority_order  :integer
#  next_program_id :integer
#
class Program < ApplicationRecord

  include Attachable
  has_paper_trail
  belongs_to :user, optional: true
  belongs_to :next_program, optional: true, class_name: 'Program'

  #in order to delete a program must not have user_programs associated
  has_many :user_programs
  has_many :program_sessions, -> { ordered_by_session }, dependent: :delete_all
  has_many :sessions, through: :program_sessions
  has_many :product_programs, dependent: :delete_all #delete this maybe
  has_many :products, through: :product_programs
  has_many :program_profiles, dependent: :delete_all
  has_many :profiles, through: :program_profiles
  has_many :program_characteristics, dependent: :delete_all
  has_many :program_implements, dependent: :delete_all
  has_many :implements, through: :program_implements

  accepts_nested_attributes_for :sessions, :product_programs, :program_characteristics, :program_profiles, :program_sessions, allow_destroy: true

  translates :name, :description

  validates :priority_order, presence: true

  has_one_attached :image
  has_one_attached :image2

  def store_implements
    program_implements.destroy_all
    implements_query.each do |implement|
      program_implements.create(implement: implement)
    end
  end

  def sessions_count
    program_sessions.count
  end
  
  def author
    User.find_by(user_id)
  end

  def exercises
    sessions&.map {|ss| ss.exercises }&.flatten
  end

  def warmup_exercises
    warmup = Program.find_by(code_name: 'warmups')
    warmup&.exercises
  end

  def implements_query
    exercises&.map {|exercise| exercise.implements}&.flatten&.uniq
  end

  def products
    return Product.where(available: true) if pro?
    nil
  end

  def max_attributes
    { strength: strength, endurance: endurance, technique: technique, 
      flexibility: flexibility, intensity: intensity }.sort_by {|k,v| v}.last(2)
  end

  def max_atributes_translations
    { 'strength'=> 'fuerza', "endurance"=> 'resistencia', "technique"=> 'tecnica', "flexibility" => 'flexibilidad', "intensity"=> 'intensidad' }
  end

  def max_attribute
    locale = I18n.locale || :en
    attr = max_attributes.last
    key = locale == :en ? attr.first.to_s : max_atributes_translations[attr.first.to_s]
    OpenStruct.new({key: key.capitalize, value: attr.last, text: nil})
  end

  def max_attribute2
    locale = I18n.locale || :en
    attr = max_attributes.first
    key = locale == :en ? attr.first.to_s : max_atributes_translations[attr.first.to_s]
    OpenStruct.new({key: key.capitalize, value: attr.last, text: nil})
  end

  def update_physical_attributes
    sessions_count = sessions.count.to_f
    sessions_count = 1 if sessions_count == 0
    self.strength = (sessions.map(&:strength).compact.sum / sessions_count).ceil
    self.endurance = (sessions.map(&:endurance).compact.sum / sessions_count).ceil
    self.technique = (sessions.map(&:technique).compact.sum / sessions_count).ceil
    self.flexibility = (sessions.map(&:flexibility).compact.sum / sessions_count).ceil
    self.intensity = (sessions.map(&:intensity).compact.sum / sessions_count).ceil
    self.save!
  end
end

app/views/admin/programs/_attributes.html.haml
%table.table-bordered
  %thead
    %tr
      %th Attribute
      %th Value
  %tbody.text-left
    - program.attributes.each do |attribute|
      %tr
        %td
          %b= attribute.first.humanize
        %td= attribute.second

app/views/admin/programs/_form.html.haml
= semantic_form_for [:admin, @program], builder: ActiveAdmin::FormBuilder do |f|
  %br
  .tabs
    %ul.nav.nav-tablist
      %li
        = link_to 'Details', '#details'
      %li 
        = link_to 'Sessions', '#sessions'
      %li
        = link_to 'Associated Products', '#products'
      %li
        = link_to 'Associated Profiles (for recomendations)', '#profiles'
    .tab-content
      .inputs{ id: 'details' }
        = f.inputs 'Program Data' do
          = f.semantic_errors
          %br
          = f.input :code_name
          %br
          = f.input :available
          %br
          = f.input :auto_generated
          %br
          = f.input :pro
          %br
          = f.input :priority_order, label: 'order (for programs suggestions)', as: :number
          = f.input :user, collection: User.where(is_admin: true).map {|user|[user.email, user.id]}
          = f.input :image, as: :file
          = f.input :image2, as: :file
          = f.input :strength
          = f.input :endurance
          = f.input :technique
          = f.input :flexibility
          = f.input :intensity
          = f.input :name_en
          = f.input :name_es
          = f.input :description_en, as: :text
          = f.input :description_es, as: :text

          = f.inputs 'Characteristics' do
            - f.has_many :program_characteristics, heading: 'Program Characteristics' do |s|
              %br
              - s.input :value_en
              %br
              - s.input :value_es
              %br
              - s.input :objective
              %br
              - s.input :_destroy, :as => :boolean, :label => "Destroy?"      

      .sessions{id: 'sessions'}
        = f.inputs 'Sessions' do
          - f.has_many :program_sessions, heading: 'Sessions' do |ses|
            .container
              .row
                .col-12
                  %br
                  - ses.input :session_id
                  %br
                  - if !ses.object.nil?
                    - if ses.object.session.present?
                      %br
                      =link_to "session #{ses.object.session.order} : #{ses.object.session.code_name || ses.object.session.name}", admin_session_path(ses.object.session)
                      %br
                      %br
                    - ses.input :_destroy, :as => :boolean, :label => "Destroy?"      
      .products{ id: 'products' }
        = f.inputs 'Products' do
          - f.has_many :product_programs, heading: 'Products' do |pr|
            .row
              .col-12
                %br
                - pr.input :product
      .profiles{ id: 'profiles' }
        = f.inputs 'Profiles' do
          - f.has_many :program_profiles, heading: 'Profiles' do |profile|
            .row
              .col-12
                %br
                - profile.input :profile
                %br
                - if !profile.object.nil?
                  - profile.input :_destroy, :as => :boolean, :label => "Destroy?"
                
    = f.actions

app/views/admin/programs/_show.html.haml
.row
  .col-8
    .container
      = render partial: 'admin/programs/attributes', locals: { program: program }
  .col-4= render partial: 'admin/versions/index', locals: { versions: program.versions.last(5) }