config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'onboarding#diagnostic'

  namespace :onboarding do
    get 'diagnostic', action: 'diagnostic'
    post 'sign_up_options'
    post 'new_sign_up'  #it has this posts as it needs to pass the user info
    post 'sign_up'
    get 'diagnostic_results'
    get 'suggested_programs'
    get 'program_detail/:program_id', action: 'program_detail'
    get 'choose_subscription/:program_id', action: 'choose_subscription'
    get 'pay_selected_plan', action: 'pay_selected_plan'
    post 'subscribe_stripe', action: 'subscribe_stripe'
  end

  namespace :buy_subscription do
    get 'offer_login'
    get 'suggested_programs'
    get 'more_programs'
    get 'program_detail'
    get 'choose_subscription'
    get 'payment_page'
    post 'subscribe_stripe'
    get 'lite_option'
    get 'thank_you_page'
    get 'upsale'
  end

 
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'
  # devise_for :users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth'
  }

  authenticate :user, -> (u) { u.is_admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'unauthorized', to: 'errors#unauthorized'
  # onboarding
  
end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController
  # each step will be set in order down diagnostic, diagnostic_results, sign_up, suggested_programs, pay_selected_plan,  thanks
  before_action :set_spanish
  before_action :check_current_or_redirect_to_diagnostic, only: [:suggested_programs, :select_plan, :pay_selected_plan, :subscribe_stripe, :thanks]
  # dont use the before_filter auhtneticate it breaks the controller

  # todo add subscribe flow
  include Devise::Controllers

  def set_spanish
    I18n.locale = :es
  end

  def diagnostic
    cookies[:program_id] = params[:program_id]
    cookies[:affiliate_code] = params[:affiliate_code]
    cookies[:offer_code] = params[:offer_code]
    @user = User.new
  end
  
  def sign_up_options#diagnostic and signup can vary
    @user = User.new(user_params)
  end
  
  def new_sign_up
    @mix_panel_id = JSON.parse(cookies[:mp_745581c49f04c81ecf450cceeea8a514_mixpanel])["distinct_id"] if cookies[:mp_745581c49f04c81ecf450cceeea8a514_mixpanel]
    @user = User.new(user_params)
  end

  def sign_up
    #  training_days_setting         :integer          default(1)
    #@user = User.new(user_params.merge({affiliate_code: cookies[:affiliate_code]}))
    @user = SignUpService.call(user_params: user_params.merge({affiliate_code_signup: cookies[:affiliate_code]}))
    if @user.persisted?
      sign_in :user, @user
      sign_in :onboarding, @user
      redirect_to onboarding_diagnostic_results_path
    end
    rescue StandardError => e
      I18n.locale = :es
      @user = User.new(user_params.merge({affiliate_code_signup: cookies[:affiliate_code]}))
      @user.validate
      render 'new_sign_up'
      #redirect_to onboarding_new_sign_up_path
  end

  def diagnostic_results
    @diagnostic = CalculateDiagnostic.new(user: current_user).call
  end

  private 
    def user_params
      params.require(:user).permit(:goal, :activity_level, :gender, :weight, :height, :body_fat, :date_of_birth, :mix_panel_id,
                                         :body_type, :newsletter_subscription, :scientific_data_usage, :email, :names, :password)
    end

    def subscription_params
      params.require(:subscription).permit(:program_id, :user_id, :product_id, :transaction_body)
    end

end

app/helpers/onboarding_helper.rb
module OnboardingHelper
end

app/views/onboarding/diagnostic.html.haml
-# :javascript
-#   (function(f,b){if(!b.__SV){var e,g,i,h;window.mixpanel=b;b._i=[];b.init=function(e,f,c){function g(a,d){var b=d.split(".");2==b.length&&(a=a[b[0]],d=b[1]);a[d]=function(){a.push([d].concat(Array.prototype.slice.call(arguments,0)))}}var a=b;"undefined"!==typeof c?a=b[c]=[]:c="mixpanel";a.people=a.people||[];a.toString=function(a){var d="mixpanel";"mixpanel"!==c&&(d+="."+c);a||(d+=" (stub)");return d};a.people.toString=function(){return a.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
-#   for(h=0;h<i.length;h++)g(a,i[h]);var j="set set_once union unset remove delete".split(" ");a.get_group=function(){function b(c){d[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));a.push([e,call2])}}for(var d={},e=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<j.length;c++)b(j[c]);return d};b._i.push([e,f,c])};b.__SV=1.2;e=f.createElement("script");e.type="text/javascript";e.async=!0;e.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
-#   MIXPANEL_CUSTOM_LIB_URL:"file:"===f.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";g=f.getElementsByTagName("script")[0];g.parentNode.insertBefore(e,g)}})(document,window.mixpanel||[]);
  
-#   // Enabling the debug mode flag is useful during implementation,
-#   // but it's recommended you remove it for production
-#   mixpanel.init('745581c49f04c81ecf450cceeea8a514', {debug: true}); 
-#   //mixpanel.track('Sign up');
.container
  .row-fluid
    .col-sm-1
    .col-sm-auto
      %h1.mt-5.text-center= I18n.t('onboarding.diagnostic.title')
      %p.light-grey.mb-2.text-center=I18n.t('onboarding.diagnostic.paragraph-1')
      %p.light-grey.border-bottom{style: 'margin-bottom: 10px; margin-top: 40px;'}
      = form_for(@user, url: onboarding_sign_up_options_path) do |f|
        %ul.stepper.parallel.vertical.stepper_style
          %li.step.active.mb-1.color_step
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.objective')
            .step-content
              .btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :goal, :loss_weight, :required => true
                  = I18n.t('onboarding.diagnostic.loose_weight')
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :goal, :gain_muscle
                  = I18n.t('onboarding.diagnostic.gain_muscle')
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :goal, :antiaging
                  = I18n.t('onboarding.diagnostic.antiaging')

          %li.step.active.mb-1.color_step
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.physical_activity')
            .step-content
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :activity_level, :sedentary, :required => true
                  = I18n.t('onboarding.diagnostic.sedentary')
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :activity_level, :medium_active
                  = I18n.t('onboarding.diagnostic.active')
                %label.btn.btn-primary.rounded-pill.btn_size
                  = f.radio_button :activity_level, :very_active
                  = I18n.t('onboarding.diagnostic.very_active')

          %li.step.active.mb-1.color_step1
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.gender')
            .step-content
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-primary.rounded-pill.btn_size{:id=>"male_button"}
                  = f.radio_button :gender, :male, :required => true
                  = I18n.t('onboarding.diagnostic.male')
                %label.btn.btn-primary.rounded-pill.btn_size{:id=>"female_button"}
                  = f.radio_button :gender, :female
                  = I18n.t('onboarding.diagnostic.female')

          %li.step.active.mb-1.color_step
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.more_info')
            .step-content
              .more-info.mb-3.md-form.md-outline.input-with-post-icon.datepicker.border-bottom
                .row
                  .col
                    %label.light-grey{:for => "fecha"}= I18n.t('onboarding.diagnostic.date_of_birth')
                  .col.text-right
                    = f.date_select :date_of_birth, :start_year => Date.current.year, :end_year => 1920, :required => true, style: 'margin-bottom: 10px; margin-right:5px;'

              .more-info.mb-3.border-bottom
                .row
                  .col
                    %label.light-grey{:for => "peso"}= I18n.t('onboarding.diagnostic.weight')
                  .col.text-right
                    = f.text_field :weight, {  required: true, style: 'margin-bottom: 10px;margin-right:5px;' }
                    Kg

              .more-info.more-info-margin.border-bottom
                .row
                  .col
                    %label.light-grey{:for => "altura"}= I18n.t('onboarding.diagnostic.height')
                  .col.text-right
                    = f.text_field :height, { required: true, style: 'margin-bottom: 10px; margin-right:5px;'  }
                    cm

          %li.step.active.mb-1.color_step
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.body_type')
            .step-content
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-primary-1.rounded
                  = f.radio_button :body_type, :strong, :required => true
                  %img{:alt => "", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images+onboarding/Grande.svg"}/
                  %br/
                  = I18n.t('onboarding.diagnostic.big')
                %label.btn.btn-primary-1.rounded
                  = f.radio_button :body_type, :medium
                  %img{:alt => "", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/Mediana.svg"}/
                  %br/
                  = I18n.t('onboarding.diagnostic.medium')
                %label.btn.btn-primary-1.rounded
                  = f.radio_button :body_type, :lean
                  %img{:alt => "", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/Pequeña.svg"}/
                  %br/
                  = I18n.t('onboarding.diagnostic.lean')

          %li.step.active.mb-1.color_step
            .step-title.waves-effect.waves-dark.pb-1.pt-1
              = I18n.t('onboarding.diagnostic.body_fat')
            .step-content
              #carouselExampleIndicators.carousel.slide{"data-interval" => "false", "data-ride" => "carousel"}
                .carousel-inner
                  .carousel-item.active.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 10, :required => true
                      %img{:alt => "First slide",:id=>"gender_photo0", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_1-b4e1c88fc4c1a82e8ccfebb11a8b9d32_10.jpg"}/
                      %br/
                      10 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 15
                      %img{:alt => "Second slide",:id=>"gender_photo1", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_2-dfb0ad44bb4894cff38f7f5589405a09.jpg"}/
                      %br/
                      15 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 20
                      %img{:alt => "Third slide", :id=>"gender_photo2", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_3-69602966b4159c1cb6683273a7ca2dca.jpg"}/
                      %br/
                      20 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 25
                      %img{:alt => "Third slide", :id=>"gender_photo3", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_4-80e2fb318f88d2996ee2ae9269d178a9.jpg"}/
                      %br/
                      25 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 30
                      %img{:alt => "Third slide", :id=>"gender_photo4", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_5-4ab4324c674970bc37b90cea8937a758.jpg"}/
                      %br/
                      30 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 35
                      %img{:alt => "Third slide", :id=>"gender_photo5", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_6-2d17cab506810fb0e2b7878aafa4e969.jpg"}/
                      %br/
                      35 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 40
                      %img{:alt => "Third slide", :id=>"gender_photo6", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_7-a93fe7cb6bc167ad7bdbaeba8b759391.jpg"}/
                      %br/
                      40 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 45
                      %img{:alt => "Third slide", :id=>"gender_photo7", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_8-391c79f7b6987f8495eb7b413ccc8af4.jpg"}/
                      %br/
                      45 %
                  .carousel-item.btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                    %label.btn.btn-primary-1.rounded.active
                      = f.radio_button :body_fat, 50
                      %img{:alt => "Third slide", :id=>"gender_photo8", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/bodyfat-picker/men_9-ced322ab38b3ee28dbe60cff81733f47_50.jpg"}/
                      %br/
                      50 %

                %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleIndicators", :role => "button"}
                  %span.carousel-control-prev-icon{"aria-hidden" => "true"}
                  %span.sr-only Previous

                %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleIndicators", :role => "button"}
                  %span.carousel-control-next-icon{"aria-hidden" => "true"}
                  %span.sr-only Next

            %p.light-grey.border-bottom{style: 'margin-bottom: 30px; margin-top: 40px;'}
            .d-grid.gap-2.d-md-flex.justify-content-md-end
              %button.btn.btn-primary.rounded-circle.me-md-2.grey-background{:type => "submit"}
                %img{:alt => "submit_img", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/arrow-right-2.png"}/
    .col-sm-1

app/views/onboarding/diagnostic_results.html.haml
.container
  .row
    .col-sm.container-text
      .row
        .col.ml-2.mr-2
          .container-text
            %h1.centrar-texto.mb-5.pt-3.pb-3.mt-5= I18n.t('onboarding.diagnostic_results.title')
            .row
              %h2.light-grey= I18n.t('onboarding.diagnostic_results.physical_evaluation')
            .row.pb-3
              %h3.col-6
              %h3.col-3.text-warning.text-right= I18n.t('onboarding.diagnostic_results.actual')
              %h3.col-3.text-danger.text-right.p-right-0= I18n.t('onboarding.diagnostic_results.ideal')
            .row.pb-3
              %h4.col-6.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.weight')
              %h4.col-3.centrar-texto.border-bottom.text-right
                = @diagnostic[:weight]
                Kg
              %h4.col-3.centrar-texto.border-bottom.text-right.p-right-0
                = @diagnostic[:ideal_weight]
                Kg
            .row.pb-3
              %h4.col-6.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.bmi')
              %h4.col-3.centrar-texto.border-bottom.text-right
                = @diagnostic[:bmi]
              %h4.col-3.centrar-texto.border-bottom.text-right.p-right-0
                = @diagnostic[:target_bmi]
            .row.pb-3
              %h4.col-6.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.body_fat')
              %h4.col-3.centrar-texto.border-bottom.text-right
                = @diagnostic[:body_fat]
                &#37
              %h4.col-3.centrar-texto.border-bottom.text-right.p-right-0
                = @diagnostic[:target_body_fat]
                &#37
            .row.margin-bottom.pb-2
              %h4.col-6.dark-grey.p-left-0.pb-2= I18n.t('onboarding.diagnostic_results.muscle_weight')
              %h4.col-3.centrar-texto.text-right
                = @diagnostic[:muscle_weight]
                Kg
              %h4.col-3.centrar-texto.text-right.p-right-0
                = @diagnostic[:ideal_muscle_weight]
                Kg
            .row.pb-3.mb-2
              %h2.mt-5.light-grey= I18n.t('onboarding.diagnostic_results.objectives')
            .row.pb-3
              %h4.col-6.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.fat_to_loose')
              %h4.col-3.border-bottom
              %h4.col-3.text-right.border-bottom.text-right.p-right-0
                = @diagnostic[:fat_to_lose]
                Kg
            .row.pb-3
              %h4.col-6.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.muscle_to_gain')
              %h4.col-3.border-bottom
              %h4.col-3.text-right.border-bottom.text-right.p-right-0
                = @diagnostic[:muscle_to_gain]
                Kg
            .row.pb-3
              %h4.col-9.dark-grey.border-bottom.p-left-0.pb-3= I18n.t('onboarding.diagnostic_results.target_calories')
              %h4.col-3.border-bottom.text-right.p-right-0
                = @diagnostic[:target_calories]
                Kcal
            .row.pb-3
              %h4.col-8.dark-grey.p-left-0= I18n.t('onboarding.diagnostic_results.weeks_to_target')
              %h4.col-4.text-right.p-right-0
                = @diagnostic[:weeks_to_target_round]
                weeks

      %form.float-right.float-down.ml-5.mt-5{:action=>"#{buy_subscription_suggested_programs_path}"}
        %button.btn.btn-primary.rounded-circle.grey-background{:type=>"submit"}
          %img.btn_button_to_buy_subscription{:alt => "submit_img", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/arrow-right-2.png"}/

app/views/onboarding/new_sign_up.html.haml
.container
  .row
    %h1.mb-4.mt-5= I18n.t('onboarding.new_sign_up.title')
    %form.needs-validation{:novalidate => ""}
    = form_for(@user, url: onboarding_sign_up_path) do |f|

      = f.hidden_field :gender
      = f.hidden_field :goal
      = f.hidden_field :activity_level
      = f.hidden_field :gender
      = f.hidden_field :weight
      = f.hidden_field :height
      = f.hidden_field :body_fat
      = f.hidden_field :body_type
      = f.hidden_field :date_of_birth
      = f.hidden_field :mix_panel_id, value: @mix_panel_id

      - if @user.errors.any?
        - @user.errors.full_messages.each do |message|
          %h3.text-danger= message
      %h2.form-group
        %label.grey.wide{:for => "name"}= I18n.t('onboarding.new_sign_up.name')
        = f.text_field :names, { class: 'wide', required: true }
        .invalid-feedback.margin-bottom
          Introduce nombre y apellidos por favor
        .p.help_text_color=I18n.t('onboarding.new_sign_up.help_name_text')
      %h2.form-group
        %label.grey.wide{:for => "email"}= I18n.t('onboarding.new_sign_up.email')
        = f.email_field :email, { class: 'wide', required: true }
        .invalid-feedback.margin-bottom
          Introduce un email válido por favor
        .p.help_text_color=I18n.t('onboarding.new_sign_up.help_email_text')

      %h2.form-group
        %label.grey.wide{:for => "password"}= I18n.t('onboarding.new_sign_up.password')
        .input-group
          = f.password_field :password, { class: 'wide', id: 's-h-pass', minlength:"6", required:'true'}
          .invalid-feedback.margin-bottom
            Introduce una contraseña válida por favor
        .p.help_text_color.mb-2=I18n.t('onboarding.new_sign_up.help_password_text')

      %h4.form-check{style: 'margin-top: 40px;'}
        %input#notifications.form-check-input.form_check_size{:type => "checkbox"}/
        %label.form-check-label.mb-4.ml-2{:for => "notifications"}= I18n.t('onboarding.new_sign_up.updates')
      %h4.form-check
        %input#terms.form-check-input.form_check_size{:required => "", :type => "checkbox"}/
        %label.form-check-label.mb-4.ml-2{:for => "terms"}= I18n.t('onboarding.new_sign_up.terminos')
      %h4.form-check
        %input#estudios.form-check-input.form_check_size{:type => "checkbox"}/
        %label.form-check-label.mb-4.ml-2{:for => "estudios"}= I18n.t('onboarding.new_sign_up.estudios')
      .d-grid.gap-2.d-md-flex.justify-content-md-end
      .row
        .col.text-left
          %button.btn.btn-danger.btn-lg.btn-block.rounded-pill.wide.fs-6.margin-bottom.btn_dimensions.mb-4{:type => "submit"}
            %h3 Crear Cuenta

app/views/onboarding/sign_up.html.haml
%h1 SIGNED UP! 

app/views/onboarding/sign_up_options.html.haml
.container.align-middle
  .row
    .col-sm-1
    .col-sm-20.round-no-scroll.text-center
      .container-text-2{style: 'margin-top:27%; margin-bottom: 50%;'}
        %img{:alt => "icon_login", :src => "https://stage-dev-new.s3-eu-west-1.amazonaws.com/onboarding/Onboarding/Images onboarding/icon_login.png"}/
        %h1.margin-bottom{style:'margin-bottom: 40px;'}= I18n.t('onboarding.sign_up_options.title')
        = form_for(@user, url: onboarding_new_sign_up_path) do |f|

          = f.hidden_field :gender
          = f.hidden_field :goal
          = f.hidden_field :activity_level
          = f.hidden_field :weight
          = f.hidden_field :height
          = f.hidden_field :body_fat
          = f.hidden_field :body_type
          = f.hidden_field :date_of_birth

          %h3.light-grey.margin-bottom.mb-5=I18n.t('onboarding.sign_up_options.paragraph-1')
          %div
            -# .btn.btn-light.btn-lg.rounded-pill.wide.fs-6.margin-bottom.btn_dimensions.mb-4
            -#   =link_to I18n.t('onboarding.sign_up_options.google'), user_google_oauth2_omniauth_authorize_path( "user[gender]" => @user.gender, "user[goal]" => @user.goal, "user[activity_level]" => @user.activity_level, "user[weight]" => @user.weight, "user[height]" => @user.height, "user[body_fat]" => @user.body_fat, "user[body_type]" => @user.body_type, "user[date_of_birth]" => @user.date_of_birth ), method: :post, :style=>'color: black;'

            -# .btn.btn-secondary.btn-lg.rounded-pill.wide.fs-6.margin-bottom.btn_dimensions.mb-4{:type => "submit"}
            -#   = link_to I18n.t('onboarding.sign_up_options.facebook'), user_facebook_omniauth_authorize_path( "user[gender]" => @user.gender, "user[goal]" => @user.goal, "user[activity_level]" => @user.activity_level, "user[weight]" => @user.weight, "user[height]" => @user.height, "user[body_fat]" => @user.body_fat, "user[body_type]" => @user.body_type, "user[date_of_birth]" => @user.date_of_birth ), method: :post, :style=>'color: white;'

            %button.btn.btn-danger.btn-lg.btn-block.rounded-pill.wide.fs-6.margin-bottom.btn_dimensions.mb-4{style: 'margin-top: 70px;', :type => "submit"}
              %h3.margin-bottom=I18n.t('onboarding.sign_up_options.email')


    .col-sm-1