config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root to: 'onboarding#diagnostic'

  namespace :onboarding do
    get 'diagnostic', action: 'diagnostic'
    post 'sign_up_options'
    post 'new_sign_up'  #it has this posts as it needs to pass the user info
    post 'sign_up'
    get 'diagnostic_results'
    get 'suggested_programs'
    get 'program_detail/:program_id', action: 'program_detail'
    get 'choose_subscription/:program_id', action: 'choose_subscription'
    get 'pay_selected_plan', action: 'pay_selected_plan'
    post 'subscribe_stripe', action: 'subscribe_stripe'
  end

  namespace :buy_subscription do
    get 'offer_login'
    get 'suggested_programs'
    get 'more_programs'
    get 'program_detail'
    get 'choose_subscription'
    get 'payment_page'
    post 'subscribe_stripe'
    get 'lite_option'
    get 'thank_you_page'
    get 'upsale'
  end

 
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end
  post '/graphql', to: 'graphql#execute'
  # devise_for :users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth'
  }

  authenticate :user, -> (u) { u.is_admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'unauthorized', to: 'errors#unauthorized'
  # onboarding
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth
  # def facebook
  #   @user = User.create_from_provider_data(request.env['omniauth.auth'])
  #   if @user.persisted?
  #     sign_in_and_redirect @user
  #     set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  #   else
  #     flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
  #     redirect_to new_user_registration_url
  #   end 
  # end

  # def failure
  #   flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
  #   redirect_to new_user_registration_url #add route to login
  # end

  # # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/omniauth_controller.rb
#facebook params
# puts request.env['omniauth.auth']
# puts request.env['omniauth.auth']['provider']
# puts request.env['omniauth.auth']['uid']
# puts request.env['omniauth.auth'].raw_info['email']
# puts request.env['omniauth.auth']['image']
class Users::OmniauthController < ApplicationController
  # todo add subscribe flow
  include Devise::Controllers
  # facebook callback
  def set_user(form_params, omni_params, provider)
    user = User.new(form_params)
    user.facebook_uid = omni_params['uid'] if provider == 'facebook'
    user.google_uid = omni_params['uid'] if provider == 'google'
    user.email = omni_params.info['email']
    user
  end

  def facebook
    user = set_user(request.env["omniauth.params"]["user"], request.env['omniauth.auth'], 'facebook')
    saved_user = SignUpService.call(user_params: user.attributes.merge({password: Devise.friendly_token[0, 20]}))
    if saved_user.persisted?
      sign_in :user, saved_user
      sign_in :onboarding, saved_user
      redirect_to onboarding_diagnostic_results_path
    else
      render plain: "There was a problem signing you in through Facebook. Please register or try signing in later. #{saved_user.errors.to_h.to_s} ola".html_safe
      #redirect_to onboarding_diagnostic_results_path
    end
  rescue ActiveRecord::RecordInvalid => e
    render plain: "There was a problem signing you in through face. Please register or try signing in later. #{e.message.to_s} ola".html_safe
  end

  # google callback
  def google_oauth2
    user = set_user(request.env["omniauth.params"]["user"], request.env['omniauth.auth'], 'google')
    saved_user = SignUpService.call(user_params: user.attributes.merge({password: Devise.friendly_token[0, 20]}))
    if saved_user.persisted?
      sign_in :user, saved_user
      sign_in :onboarding, saved_user
      redirect_to onboarding_diagnostic_results_path
    else
      render plain: "There was a problem signing you in through google. Please register or try signing in later. #{saved_user.errors.to_h.to_s} ola".html_safe
      #redirect_to onboarding_diagnostic_results_path
    end
  rescue ActiveRecord::RecordInvalid => e
    render plain: "There was a problem signing you in through google. Please register or try signing in later. #{e.message.to_s} ola".html_safe
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
    redirect_to new_user_registration_url #add route to login
  end

  # def passthru
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/views/admin/users/_attributes.html.haml
- if user.is_pro
  %h1 PRO
- else
  %h1 FREE
%table.table-bordered
  %thead
    %tr
      %th Attribute
      %th Value
  %tbody.text-left
    - user.attributes.each do |attribute|
      %tr
        %td
          %b= attribute.first.humanize
        %td= attribute.second

app/views/admin/users/_form.html.haml
= semantic_form_for [:admin, @user], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs 'User  Data' do
    = f.semantic_errors
    = f.input :email
    = f.input :affiliate_code
    = f.input :gender
    = f.input :date_of_birth
    = f.input :activity_level
    = f.input :goal
    = f.input :body_type
    = f.input :body_fat
    = f.input :height
    = f.input :weight
    = f.input :updated_at
    = f.input :created_at
    = f.input :newsletter_subscription
    %br
    = f.input :names
    = f.input :last_name
    = f.input :facebook_uid
    = f.input :workout_setting_voice_coach
    = f.input :workout_setting_sound
    = f.input :workout_setting_vibration
    = f.input :workout_setting_mobility
    = f.input :workout_setting_cardio_warmup
    = f.input :workout_setting_countdown
    = f.input :scientific_data_usage
    = f.input :notifications_setting
    %br
    %br
    = f.input :training_days_setting, collection: [*1..7]
    = f.input :language
    = f.input :country, as: :string
    = f.input :points
    = f.input :t1_push                       
    = f.input :t1_core                       
    = f.input :t1_legs                       
    = f.input :t1_full                       
    = f.input :t1_push_exercise              
    = f.input :t1_pull_up                    
    = f.input :t2_reps                       
    = f.input :t2_steps                      
    = f.input :t2_reps_push                  
    = f.input :t2_reps_core                  
    = f.input :t2_reps_legs                  
    = f.input :t2_reps_full                  
    = f.input :t2_time_push                  
    = f.input :t2_time_core                  
    = f.input :t2_time_legs                  
    = f.input :t2_time_full                  
    = f.input :t1_full_exercise              
    = f.input :t1_pull_up_exercise
  = f.actions

app/views/admin/users/_show.html.haml
.row
  .col-8
    .tabs
      %ul.nav.nav-tablist
        %li
          = link_to 'Details', '#details'
        %li 
          = link_to 'User programs', '#user_programs'
        %li 
          = link_to 'Subscriptions', '#subscriptions'
      .tab-content
        .details{ id: 'details' }
          .container
            = render partial: 'admin/users/attributes', locals: { user: user }
        .user_programs{ id: 'user_programs'}
          .container
            %h1 
              User Programs Info
            - user.user_programs.each do |up|
              = "PROGRAMA: #{up.program.name}, ID: #{up.program.id}, CODENAME: #{up.program.code_name}"
              %br
            %h3=link_to( "CURRENT PROGRAM id: #{user.current_program&.id} - #{user.current_program&.name}", admin_programs_path(user.current_program))
            %h1 EXECUTIONS
            - user.last_week_executions.each do |execution|
              =  link_to "destroy execution #{execution.id}: #{execution.session.name} : #{execution.created_at}", destroy_execution_admin_user_path(id: user.id, execution_id: execution.id)
              %br
        .subscriptions{ id: 'subscriptions'}
          .container
            = render partial: 'admin/users/subscriptions', locals: { user: user }
   
  .col-4= render partial: 'admin/versions/index', locals: { versions: user.versions.last(5) }

app/views/admin/users/_subscriptions.html.haml
%h2 subs data
= semantic_form_for [:admin, user], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs 'Subs data' do
    = f.semantic_errors
    - f.has_many :subscriptions, heading: 'subscriptions' do |sb|
      - sb.semantic_errors
      - sb.input :product, input_html: {required: true}, required: true   
      - sb.input :program
      - sb.input :transaction_body
      - sb.input :status
      - sb.input :start_date
      - sb.input :end_date
      - sb.input :cancelled
      %br
      - #sb.store_metadata      :jsonb
      - sb.input :cancellation_reason
      - sb.input :created_at
      %br
    = f.actions
  